FROM richarvey/nginx-php-fpm:latest

COPY . .

# Image config
ENV SKIP_COMPOSER 1
ENV WEBROOT /var/www/html/public
ENV PHP_ERRORS_STDERR 1
ENV RUN_SCRIPTS 1
ENV REAL_IP_HEADER 1

# Laravel config
ENV APP_ENV production
ENV APP_DEBUG false
ENV LOG_CHANNEL stderr[[1](https://www.google.com/url?sa=E&q=https%3A%2F%2Fvertexaisearch.cloud.google.com%2Fgrounding-api-redirect%2FAUZIYQHwFpMXZX2qwlvBoeqz00D1B4HZUjcDOQfXmSN-njD6ReofH59xCuWtB_SWRkyf9WwnoC0121TiwQQJXATFNM_hW0fbpR-jZ-yUqFKd_Ohid_Y0S9qG_n52QyruhpciqUSesbRy1jM%3D)]

# Allow composer to run as root
ENV COMPOSER_ALLOW_SUPERUSER 1[[1](https://www.google.com/url?sa=E&q=https%3A%2F%2Fvertexaisearch.cloud.google.com%2Fgrounding-api-redirect%2FAUZIYQHwFpMXZX2qwlvBoeqz00D1B4HZUjcDOQfXmSN-njD6ReofH59xCuWtB_SWRkyf9WwnoC0121TiwQQJXATFNM_hW0fbpR-jZ-yUqFKd_Ohid_Y0S9qG_n52QyruhpciqUSesbRy1jM%3D)]

CMD ["/bin/sh", "-c", "php artisan migrate --force && php artisan storage:link && php artisan optimize:clear && /start.sh"]