FROM richarvey/nginx-php-fpm:latest

COPY . .

# Image config
ENV SKIP_COMPOSER 1
ENV WEBROOT /var/www/html/public
ENV PHP_ERRORS_STDERR 1
ENV RUN_SCRIPTS 1
ENV REAL_IP_HEADER 1

# Laravel config
ENV APP_ENV production
ENV APP_DEBUG false
ENV LOG_CHANNEL stderr

# Allow composer to run as root
ENV COMPOSER_ALLOW_SUPERUSER 1

# --- STEP 1: Install Dependencies (Fixes "autoload.php" error) ---
RUN composer install --no-dev --optimize-autoloader

# --- STEP 2: Fix Permissions ---
RUN chown -R www-data:www-data /var/www/html

# --- STEP 3: Start Command (Create SQLite DB -> Migrate -> Start) ---
CMD ["/bin/sh", "-c", "touch /var/www/html/database/database.sqlite && php artisan migrate --force && php artisan storage:link && php artisan optimize:clear && /start.sh"]